# Build settings

name: DOCType

markdown: kramdown
permalink: pretty

url: http://ashenheim.github.io/docs

port: 4000

sass:
  sass_dir: assets/css
  style: :compressed # :nested, :expanded, :compact, :compressed

exclude: [
  'node_modules',
  'sass_cache',
  'Gruntfile.js',
  'package.json',
  '*.map']

collections:
- sections